apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test
spec:
  containers:
  - name: test
    image: busybox
    command: [ "sleep", "1000" ]
    volumeMounts:
    - name: testvol
      mountPath: /host
  volumes:
  - name: testvol
    hostPath:
      path: /etc
