apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  namespace: jegan 
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: bitnami/nginx:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

