apiVersion: v1
kind: Pod
metadata:
  name: violating-pod
  namespace: jegan
spec:
  containers:
  - name: nginx
    image: bitnami/nginx:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: true

