apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: vault-psa-demo
data:
  config.hcl: |
    exit_after_auth = false
    pid_file = "/tmp/pidfile"

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "demo-role"
        }
      }

      sink "file" {
        config = {
          path = "/vault/secrets/secret.txt"
        }
      }
    }

    cache {
      use_auto_auth_token = true
    }

    listener "file" {
      address = "unix:///tmp/agent.sock"
      tls_disable = true
    }

