apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-demo
  namespace: vault-psa-demo
spec:
  serviceAccountName: vault-auth
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - name: vault-secrets
    emptyDir: {}
  - name: vault-agent-config
    configMap:
      name: vault-agent-config
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat /vault/secrets/secret.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /vault/secrets
      name: vault-secrets
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  - name: vault-agent
    image: hashicorp/vault:1.13.0
    args: ["agent", "-config=/vault/config/config.hcl"]
    volumeMounts:
    - mountPath: /vault/secrets
      name: vault-secrets
    - mountPath: /vault/config
      name: vault-agent-config
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

