apiVersion: v1
kind: Pod
metadata:
  name: vault-example
  namespace: jegan 
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: vault-auth
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat /vault/secrets/secret.txt && sleep 3600"]
    volumeMounts:
    - name: vault-secrets
      mountPath: /vault/secrets
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

  - name: vault-agent
    image: hashicorp/vault:1.13.0
    args: ["agent", "-config=/vault/config/config.hcl"]
    volumeMounts:
    - name: vault-secrets
      mountPath: /vault/secrets
    - name: vault-config
      mountPath: /vault/config
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

  volumes:
  - name: vault-secrets
    emptyDir: {}
  - name: vault-config
    configMap:
      name: vault-agent-config

